version: "3.7"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=codetest
      - POSTGRES_USER=codetest
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  ingestion:
    image: orchidesr/ingestion:v1.0.0
    restart: on-failure
    ports: 
      - 8080:8080
    volumes:
      -  /usr/src/app/node_modules
      - ./ingestion:/usr/src/app
    depends_on:
      - database

  transformer:
    image: orchidesr/transformer:v1.0.0
    restart: on-failure
    ports: 
      - 5000:5000
    volumes:
      -  /usr/src/app/node_modules
      - ./transformer:/usr/src/app
      - ./data:/usr/src/app/

